### PR TITLE
Attempting GHA release workflow

### LINKED ISSUE #487: GHA for release and publish
Create a GitHub Action for releasing `spaghetti` on GitHub and publishing it to PyPI.

* still must include several manual steps:
  * prior to tagged release:
    - set release_date and start_date in cell 1 of `tools/gitcount.ipynb`
  * following tagged release:
    - update `CHANGELOG.md`

For guidance see:
  * pysal/submodule_template#29
  * spatialucr/geosnap#221

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR attempts to resolve #487

### CODE REVIEW

**Comment by knaaptime** [comment]
I should've added that if you copy the changes in my gitcount notebook, you dont need to set anything manually

**Comment by knaaptime** [comment]
and because it regenerates changelog.md each time, you can just delete it from the repo

**Comment by jGaboardi** [comment]
oooooh. very nice.

**Comment by jGaboardi** [comment]
I'll try again in #489

**Comment by jGaboardi** [comment]
@knaaptime 

> I should've added that if you copy the changes in my gitcount notebook, you dont need to set anything manually. and because it regenerates changelog.md each time, you can just delete it from the repo.

But does it regenerate `changelog.md`? There does not seem to be any release notes or a `changelog.md` for the [`geosnap v0.3.01`](https://github.com/spatialucr/geosnap/releases/tag/v0.3.01). The most recent one is from [`v0.2.0`](https://github.com/spatialucr/geosnap/tree/master/tools).

I'd like to keep the traditional `CHANGELOG.md` in the root directory and prepend version changes it, while creating release notes. What do you think about my current workflow for doing that? Shall we continue this discussion in #489?

**Comment by knaaptime** [comment]
i think the issue was i screwed the tag up. The [tests](https://github.com/knaaptime/geosnap/releases/tag/v0.3.0) on my fork got the correct changelog. The changelog is generated as part of the workflow and its just used to upload as the release notes on github. It doesn't get committed to the repo afterward

I was originally trying to keep each changelog, but it was difficult to get the correct one uploaded during the release, and again, i didnt want (or know how) to have the workflow commit to the repo. Given that, i figured it was acceptable to just go back to each tag if you really need the changelog (or, you could generate one yourself by plugging in the dates into the notebook)

all that to say, i'm cool with keeping the older changelogs around if you can figure out how

**Pull request merged**
