### PR TITLE
Attempting GHA release workflow #2

### PR DESCRIPTION
**Pull request by jGaboardi**
Following #488 

Addressing #487

### CODE REVIEW

**Comment by jGaboardi** [comment]
@knaaptime I have implemented your [`changelog`](https://github.com/spatialucr/geosnap/blob/master/tools/gitcount.ipynb) solution, and will simply update the root `CHANGELOG.md` manually from the release notes in order to keep an easily accessible running history of the project.

**Comment by jGaboardi** [comment]
Currently failing on [my fork](https://github.com/jGaboardi/spaghetti/actions/runs/94659497) due to syntax issues.

**Comment by jGaboardi** [comment]
@knaaptime I'm banging my head against the wall over here trying to figure out how to properly authenticate the PyPI upload. Can't seem to get to `__token__`/`password`/`secret` format correct as described in the [`pypi`](https://pypi.org/help/#apitoken) and [`pypa`](https://github.com/pypa/gh-action-pypi-publish#usage) docs. Here is the current failure from tag `v1.5.0.rc10` in [`jGaboardi/spaghetti`](https://github.com/jGaboardi/spaghetti/runs/641189985#step:11:16). Any help would be awesome.

**Comment by knaaptime** [comment]
that __token__ part wasnt online when I set things up so didnt encounter that particular hurdle. Looks like you arent using it in this pr though...

so `secrets.PYPI_PASSWORD` is case sensitive, so PYPI_PASSWORD needs to be all caps in the spaghetti setttings. Droping that api token stuff means PYPI_PASSWORD should be your password with no prefix or anything. is that how you have it setup now?

**Comment by jGaboardi** [comment]
> that token part wasnt online when I set things up so didnt encounter that particular hurdle. Looks like you arent using it in this pr though...

Maybe I am not understanding `tags` correctly. I have been tagging my commits and pushing them to origin (`git push origin [tag name]`) and they are running directly on `jGaboardi/spaghetti`. The `__token__` parameter is in the `.yml` there. Should I also be pushing the tags to `upstream`? 

> so `secrets.PYPI_PASSWORD` is case sensitive, so PYPI_PASSWORD needs to be all caps in the spaghetti setttings. Droping that api token stuff means PYPI_PASSWORD should be your password with no prefix or anything. is that how you have it setup now?

I believe this is how I have it set up, but GitHub won't allow the editing of secrets (just removal). So the `__token__` parameter must be super new. I wonder if the current workflow for `geosnap` will still work?

At any rate, here is what I will try:
 1. with `__token__`
    * remove/reset both secrets in `pysal/spaghetti` and `jGaboardi/spaghetti` to make sure they are identical (with the `pypi-` prefix in the password)
    * push
 2. drop the api token from `.yml`
    * remove/reset both secrets in `pysal/spaghetti` and `jGaboardi/spaghetti` to make sure they are identical (without the `pypi-` prefix in the password)
    * push

**Comment by knaaptime** [comment]
keep in mind i think if you're using option 1

>with __token__
remove/reset both secrets in pysal/spaghetti and jGaboardi/spaghetti to make sure they are identical (with the pypi- prefix in the password)
push

then the PYPI_PASSWORD should be set to the value of the api token (which presumably includes a `pypi-` prefix)

but if option 2, then PYPI_PASSWORD should be *your* pypi password

**Comment by jGaboardi** [comment]
> keep in mind i think if you're using option 1
> 
> > with **token**
> > remove/reset both secrets in pysal/spaghetti and jGaboardi/spaghetti to make sure they are identical (with the pypi- prefix in the password)
> > push
> 
> then the PYPI_PASSWORD should be set to the value of the api token (which presumably includes a `pypi-` prefix)
> 
> but if option 2, then PYPI_PASSWORD should be _your_ pypi password

I think this is what I tried first. I will do this again.

**Comment by jGaboardi** [comment]
@knaaptime This seems to be working for [my fork's release workflow](https://github.com/jGaboardi/spaghetti/actions/runs/94752912/workflow) now (see pypi version [here](https://pypi.org/project/spaghetti/1.5.0rc12/)). It was only successful after generating the PyPI API token, so you may need to update the `geosnap` workflow for the next release.

After merging this PR, is the next step pushing a tag directly to `upstream`?

**Comment by knaaptime** [comment]
i havent fully tested, but i think yes. Merge this, then push a tag directly upstream. Otherwise, the package will build on your account and push to pypi and this workflow will fail upsream because pypi will reject the package as already existing (which is what happend last on geosnap)

**Pull request merged**
