### PR TITLE
Update travis CI for new testing schema

### PR DESCRIPTION
**Pull request by jGaboardi**
Attempting to address #299

### CODE REVIEW

**Comment by jGaboardi** [comment]
Travis CI not kicking, so may have bad syntax in `.travis.yml`

**Comment by jGaboardi** [comment]
In this PR I have attempted to implement both [the alternative testing structure](https://github.com/pysal/pysal/pull/1130) advised by @ocefpaf while maintaining the legacy [`allow_failures`](https://github.com/pysal/spaghetti/blob/a177de609070b5e3f655660895b8ed03e5a23fd4/.travis.yml#L19-L27) options used when testing against the bleeding edge `libpysal` (`PYSAL_PYPI=false`) and when testing with the [`requirements_plus.txt`](https://github.com/pysal/spaghetti/blob/master/requirements_plus.txt) soft dependencies (`PYSAL_PLUS=true`). [Due to not being able to have named jobs through matrix expansion](https://docs.travis-ci.com/user/customizing-the-build/#naming-jobs-within-matrices), it appears that all combinations must be enumerated with the `include` function. With this new matrix of tests ([12 in total](https://travis-ci.org/pysal/spaghetti/builds/576513444?utm_source=github_status&utm_medium=notification)), the `tarball` type is tested four times. If I understand correctly, the `tarball` tests are simply checking the distribution (not running any other actual tests) so limiting these to one check would be acceptable. Am I correct in this?

I would appreciate any/all reviews suggestions.

**Comment by jGaboardi** [comment]
@sjsrey  Do you have any thoughts on this before merging?

@ocefpaf  If you have a moment, would you be able to review this PR?

**Comment by ocefpaf** [comment]
> @ocefpaf If you have a moment, would you be able to review this PR?

Sorry, I was away the past two weeks. LGMT!

PS: we should probably abstract most of that into a ci-helper so people can easily copy-n-paste it into new projects.

**Comment by jGaboardi** [comment]
@ocefpaf Thanks!

> PS: we should probably abstract most of that into a ci-helper so people can easily copy-n-paste it into new projects.

For example?

**Comment by ocefpaf** [comment]
> For example?

Something like https://github.com/astropy/ci-helpers. I'll try to put something together.

**Pull request merged**
