### PR TITLE
Prune CI testing matrix

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR addresses #615. I settled on (c) from that issue with an added Ubuntu/Python 3.9 base environment to run tests without the optional `geopandas` dependency.

### CODE REVIEW

**Comment by jGaboardi** [comment]
Pruned matrix cuts test runtime to [under 10 minutes](https://github.com/pysal/spaghetti/actions/runs/789252199). I think this is a good compromise @martinfleis. Thoughts?

**Comment by martinfleis** [comment]
I would suggest having the majority of tests based on stable libpysal and one env on master. So instead of installing dev version to every env, we would install it to one. We should try to replicate users' environments here and they will use the latest release in most cases, not master.

It means adding one, probably ubuntu-based env with DEV flag and keeping the condition for git installation as it is.

**Comment by jGaboardi** [comment]
> I would suggest having the majority of tests based on stable libpysal and one env on master. So instead of installing dev version to every env, we would install it to one. We should try to replicate users' environments here and they will use the latest release in most cases, not master.
> 
> It means adding one, probably ubuntu-based env with DEV flag and keeping the condition for git installation as it is.

This is a good idea. I'll update the PR.

**Comment by martinfleis** [comment]
One minor requests. GHA has an annoying tendency to trim the name of the test. If we call them all `micromamba unittests (...)` it is hard to see what they are apart from OS:
Screenshot 2021-04-27 at 19 14 38

Can we use just `${{ matrix.os }}, ${{ matrix.environment-file }}` as a `name`? I think it is clear these are tests.

**Comment by jGaboardi** [comment]
> One minor requests. GHA has an annoying tendency to trim the name of the test. If we call them all `micromamba unittests (...)` it is hard to see what they are apart from OS:
> Screenshot 2021-04-27 at 19 14 38
> 
> Can we use just `${{ matrix.os }}, ${{ matrix.environment-file }}` as a `name`? I think it is clear these are tests.

Another great insight. I'll make that change and merge.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
