### PR TITLE
Spaghetti/update travis

### PR DESCRIPTION
**Pull request by jGaboardi**
- corrected spelling error in email address

- dropped python 2 from testing

### CODE REVIEW

**Comment by ljwolf** [comment]
I'm addressing the shapely issue [here](https://github.com/pysal/libpysal/pull/65). 

Can you add spaghetti to nightli.es?

**Comment by ljwolf** [comment]
This fails because it used to be possible to initialize a network without providing data. 

So, things that expect `in_shp` to be nonnull fail, since it can be `None`

**Comment by jGaboardi** [comment]
@ljwolf all travis checks are passing

**Comment by ljwolf** [comment]
:tada:

**Pull request merged**
