### PR TITLE
[ENH] moving towards multi-platform testing

### PR DESCRIPTION
**Pull request by jGaboardi**
When complete this PR will address:
 * #407 
 * #417 
 * (possibly) #322

### CODE REVIEW

**Comment by jGaboardi** [comment]
pysal/libpysal#247
pysal/libpysal#248
pysal/libpysal#250
pysal/libpysal#251

**Comment by jGaboardi** [comment]
@sjsrey All builds are passing with the new `pytest`/`codecov` scheme and environment-style testing for TravisCI (based on those in `libpysal`), which `appveyor` uses to piggyback tests. However, I think `appveyor` isn't being triggered because it isn't in `master` yet. If you could give this PR a once over, I will merge it in to see if `appveyor` kicks in and debug from there (or revert).

Note sure if this is related, but when I try to authorize `appveyor` for `spaghetti` (first image), I am getting a message that the action can only be an organization owner (second image).

Screenshot 2020-02-17 19 07 26


Screenshot 2020-02-17 19 06 49

**Comment by sjsrey** [comment]
I authorized appveyor on pysal/spaghetti so this should trigger a build.

**Comment by sjsrey** [comment]
The example dataset is [not installed](https://ci.appveyor.com/project/SergeRey/spaghetti/build/job/jebu3791fhkp41lb#L391).

**Comment by jGaboardi** [comment]
> The example dataset is not installed.

Thanks! This is being addressed in #419 

Also, I am trying to get the `appveyor` badge for `spaghetti`, but it seems like I don't have the permissions to even view the `pysal/spaghetti` stuff for `appveyor`, only the `jGaboardi/spaghetti` stuff.

**Comment by sjsrey** [comment]
[Build status](https://ci.appveyor.com/project/SergeRey/spaghetti)

**Comment by jGaboardi** [comment]
Both that badge (and now I see the [one for `libpysal` is too](https://ci.appveyor.com/project/SergeRey/libpysal/branch/master)) are for your repos:

--> https://ci.appveyor.com/project/SergeRey/spaghetti
--> https://ci.appveyor.com/project/SergeRey/libpysal/branch/master

We should be able to get actual project repo badges, like [`scipy`](https://github.com/scipy/scipy#scipy) has:

--> https://ci.appveyor.com/project/scipy/scipy

**Comment by sjsrey** [comment]
the pysal org account is under my SergeRey appveyor account. 
my forks are under my sjsrey appveyor account.

**Comment by sjsrey** [comment]
WIll have to investigate migration: https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

**Comment by jGaboardi** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sjsrey** [comment]
For the failing import, maybe move the load_example inside the setup for the test:

```
from libpysal import examples
examples.load_example("newHaven")
pth = examples.get_path("whateverfileyouwant")
```

**Comment by sjsrey** [comment]
[Build status](https://ci.appveyor.com/project/pysal/spaghetti)

**Comment by jGaboardi** [comment]
>For the failing import, maybe move the load_example inside the setup for the test:

Excellet idea! And awesome on the accounts/badge.

**Comment by jGaboardi** [comment]
fix for #419

> For the failing import, maybe move the load_example inside the setup for the test:
>```
>from libpysal import examples
>examples.load_example("newHaven")
>pth = examples.get_path("whateverfileyouwant")
>```

**Pull request merged**
