### PR TITLE
switching to github docs as per #301

### PR DESCRIPTION
**Pull request by jGaboardi**
Addressing #301

### CODE REVIEW

**Comment by weikang9009** [comment]
I would suggest removing everything in [doc/_build](https://github.com/jGaboardi/spaghetti/tree/git_docs/doc/_build) or simply removing this folder.

**Comment by weikang9009** [comment]
Great! Thanks!

You might also need to copy [.nojekyll](https://github.com/pysal/submodule_template/tree/master/docs) to docs/

**Comment by jGaboardi** [comment]
jeez... I am the king of easy mistakes today... LOL

**Comment by weikang9009** [comment]
It is easy to miss. no worries.

**Pull request merged**
