### PR TITLE
switching from pip to conda for reqs install resolves .travis error

### PR DESCRIPTION
**Pull request by jGaboardi**
Addressing #248

### CODE REVIEW

**Comment by jGaboardi** [comment]
Will be attempting this in `libpysal` to potential to solve pysal/libpysal#127

**Comment by jGaboardi** [comment]
may concern pysal/libpysal#129

**Comment by jGaboardi** [comment]
may concern pysal/libpysal#127

**Comment by weikang9009** [comment]
@jGaboardi Any idea why `pip intall` fails? I always prefer `pip install` since it seems to be quicker than `conda install`. But if it incurs more issues, I might need to test more next time before deciding on `pip install`.

**Comment by jGaboardi** [comment]
@weikang9009 It has to do with the the dependencies for `geopandas` and how they sometimes don't  play nicely together when newer versions are released. By using `conda-forge` with the new `strict` channel enforcement this has been resolved.

@ocefpaf Did I explain this correctly?

**Comment by ocefpaf** [comment]
Yep. That's pretty much it. We update our docs on the topic btw: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Pull request merged**
