### PR TITLE
add Network.Moran method

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR partially addresses #586 by...
* adding a `Network.Moran` method to the code base that was previously only found in the Tutorials;
* add tests for the `Network.Moran` method;
* rerunning notebooks.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@slumnitz @knaaptime @jeffcsauer @sjsrey 

I am having a tough time diagnosing this failure. Any thoughts/advice/etc. would be super.
* [new `Moran` method](https://github.com/pysal/spaghetti/pull/595/files#diff-904dccd171d058570c299fa84c69a589771b0006f38f1c37146276609811e9c2R2545) that calls `esda.Moran` (originally found in a [tutorial](https://pysal.org/spaghetti/notebooks/network-spatial-autocorrelation.html#1.-ESDA-—-Exploratory-Spatial-Data-Analysis-with-pysal/esda))
* [moran tests](https://github.com/pysal/spaghetti/pull/595/files#diff-aca03288efbbced9e7ea87cee5a8c08cd9d04c25141a9934d9a317225f01067dR768) passing on [macOS](https://github.com/pysal/spaghetti/runs/1765070864) & [Windows](https://github.com/pysal/spaghetti/runs/1765340639) — Python 3.6, 3.7, 3.8, 3.9.
* moran tests failing on Ubuntu — Python [3.6](https://github.com/pysal/spaghetti/runs/1765430238#step:9:128), [3.7](https://github.com/pysal/spaghetti/pull/595/checks?check_run_id=1765466778#step:9:128), [3.8](https://github.com/pysal/spaghetti/runs/1764976728?check_suite_focus=true#step:9:130), [3.9](https://github.com/pysal/spaghetti/pull/595/checks?check_run_id=1765532439#step:9:129).
* within `esda` itself `Moran` is being successfully tested on [all three platform & Python 3.6-8](https://github.com/pysal/esda/blob/7e51b1a45e535ffba82f46647a24cba38aac9777/.github/workflows/unittests.yml#L18)

**Comment by jGaboardi** [comment]
`y` values [1263c8b] (observation counts along arcs) and `dict` sorting [9f02ea1] don't appear to be the problem. Maybe it's something in `numpy` or `scipy.stats` that causing this down from within `esda`... but then again CI is still passing for `esda`. I'm at a loss.

**Comment by jeffcsauer** [comment]
Could this be a ubuntu specific issue? As you noted, it's passing on macOS and Windows. I can try to spin up a ubuntu vm in a bit and see what's going on

**Comment by jGaboardi** [comment]
> Could this be a ubuntu specific issue? As you noted, it's passing on macOS and Windows. I can try to spin up a ubuntu vm in a bit and see what's going on

Yeah, I would be surprised at this point if it *wasn't* an Ubuntu specific issue.

**Comment by jGaboardi** [comment]
got an Ubuntu machine up. here is a quick [gist](https://gist.github.com/jGaboardi/2510131348bda31fd808eaaf399a6413) "demonstrating" incorrect result on Ubuntu.

**Comment by jeffcsauer** [comment]
@jGaboardi have not fully diagnosed the issue, but identified at least one place within the `Moran.py` function where calculations start to diverge. Specifically:

```python
 def __calc(self, z):
        zl = slag(self.w, z)
        print(zl[0])
```

First few numbers from Windows:
```
0.05280528052805272
11.471452145214515
0.5528052805280528
91.44042904290428
```

First few numbers from Ubuntu:
```
0.05280528052805272
9.136413641364133
-0.19719471947194722
29.333388338833892
```

True divergence in the function might start earlier, that was just the most crucial calculation that jumped out at me as likely being different (lucky guess?). 

Here are my `watermark`s:

Windows:
```
Last updated: 2021-01-26T21:54:05.283616-06:00

Python implementation: CPython
Python version       : 3.8.3
IPython version      : 7.16.1

Compiler    : MSC v.1924 64 bit (AMD64)
OS          : Windows
Release     : 10
Machine     : AMD64
Processor   : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
CPU cores   : 8
Architecture: 64bit

Watermark: 2.1.0

esda     : 2.3.6
libpysal : 4.3.0
numpy    : 1.19.0
scipy    : 1.5.1
spaghetti: 1.5.0
```


Ubuntu:
```
Last updated: 2021-01-26T14:56:44.334798-06:00

Python implementation: CPython
Python version       : 3.8.7
IPython version      : 7.19.0

Compiler    : GCC 5.4.0 20160609
OS          : Linux
Release     : 4.4.0-19041-Microsoft
Machine     : x86_64
Processor   : x86_64
CPU cores   : 8
Architecture: 64bit


Watermark: 2.1.0

esda     : 2.3.6
numpy    : 1.19.5
scipy    : 1.6.0
spaghetti: 1.5.6
libpysal : 4.3.5

```

I'll keep looking into it.

**Comment by jGaboardi** [comment]
@jeffcsauer This is a nice find and we have something more concrete to focus on. Here is a rehash of our convo on gitter for the sake of openness:

 > ... it looks like it may be happening in [`spatial_lag.lag_spatial()`](https://github.com/pysal/libpysal/blob/57c0b3d2918fa10844de43fae913e57dc90f1448/libpysal/weights/spatial_lag.py#L10)  (aliased as `slag`) where `w.sprase`is present, which is itself being built from [`weights._build_sparse()`](https://github.com/pysal/libpysal/blob/57c0b3d2918fa10844de43fae913e57dc90f1448/libpysal/weights/weights.py#L390) and uses [`scipy.sparse.crs_matrix()`](https://github.com/pysal/libpysal/blob/57c0b3d2918fa10844de43fae913e57dc90f1448/libpysal/weights/weights.py#L406).

**Comment by jGaboardi** [comment]
Here is a workflow in [macOS](https://gist.github.com/jGaboardi/502b5e9a48d5e69fef0c2903bcb96d50) and [ubuntu](https://gist.github.com/jGaboardi/1b60efc3d8ff46e6ca5bf63fe327d1fd) demonstrating the same difference in the result for `esda.Moran.I` for the empirical data, ***but*** identical results for small, synthetic data.

**Pull request merged**
