### PR TITLE
Spag/analysis cosmetics

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR is merely rearranging the classes/functions in `analysis.py` for cosmetics and adding spaces to comply with PEP8. There are no functional changes to the existing classes and functions.

### CODE REVIEW

**Comment by sjsrey** [comment]
Does this include #16? If so we can merge this one and close #16.

**Comment by jGaboardi** [comment]
I did two separate commits: 
* #16 for the `api.py`; and 
* #17 for some minor clean up of `analysis.py`

Should I:
* merge the two separately **or**
* merge #17 and close #16? 

I am bit confused about the difference between those two choices. Which is best?

**Comment by sjsrey** [comment]
#17 includes the one commit in #16 (https://github.com/pysal/spaghetti/pull/17/commits/d054f7edd276ad74a8693b6d626ae13251bbabc3) so merging #17 and closing #16 seems the way to go.

**Comment by jGaboardi** [comment]
Welp, they both merged at once when I merged in #17

**Comment by sjsrey** [comment]
all good.

**Comment by jGaboardi** [comment]
@sjsrey Can you give some direction as far as adding tests for `api.py`? I am not sure how to proceed with that.

**Comment by sjsrey** [comment]
@jGaboardi for testing api.py have a look at how we are going to be doing it for giddy: 

- the api:  [api.py](https://github.com/sjsrey/giddy/blob/api/giddy/api.py)
- the tests: [test_api.py](https://github.com/sjsrey/giddy/blob/api/giddy/tests/test_api.py)

**Pull request merged**
